services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    hostname: postgres-database
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: pL5dT78Uyu
        POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - database-postgres:/var/lib/postgresql/data
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120

volumes:
  database-postgres: